# Generated by Django 2.0.3 on 2018-04-11 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('doctor', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('mi', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=150)),
                ('previous_name', models.CharField(max_length=150)),
                ('mailing_address', models.CharField(max_length=150)),
                ('city_state_code', models.CharField(max_length=128)),
                ('home_phone', models.CharField(max_length=15)),
                ('cell_phone', models.CharField(max_length=15)),
                ('work_phone', models.CharField(max_length=15)),
                ('method_contact', models.CharField(choices=[('v', 'Voice'), ('t', 'Text')], max_length=5)),
                ('date_birth', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=8)),
                ('emergency_contact', models.CharField(max_length=128)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=128)),
                ('notes', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc.Appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mc.Patient'),
        ),
    ]
