# Generated by Django 2.0.3 on 2018-04-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0002_remove_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='treatmenthistory',
            name='date',
            field=models.DateField(max_length=50),
        ),
    ]
