# Generated by Django 2.0.3 on 2018-04-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0003_auto_20180411_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='treatmenthistory',
            name='date',
            field=models.DateField(),
        ),
    ]
