# Generated by Django 2.0.3 on 2018-04-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0005_patient_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
