# Generated by Django 2.0.3 on 2018-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0006_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created',
            field=models.DateField(),
        ),
    ]
