# Generated by Django 2.0.3 on 2018-04-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0009_appointment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
