# Generated by Django 2.0.3 on 2018-04-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc', '0011_auto_20180417_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='method_contact',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], max_length=5),
        ),
    ]
